### ISSUE TITLE
No output file with --video 0

### ISSUE THREAD

**Issue by ykn96** [ankit16-py/YOLOv3-KCF-Fast-Object-Tracker#2]
Hi ! Sorry if this is a silly question... I tried running your repo's code. With the following
```
python3 tracker.py --video 0
````
In hopes of using my webcam's feed for the tracking.

However, no output is returned by the terminal, and no output video file is produced.
Could you advise on how might i proceed with usng the webcam, and also seeing the camera feed on screen ?

**Comment by ankitVP77** [comment]
Hey! This is not at all a silly question. You can't use the above command because it passes a string '0' to the cv2's capture object instead of an int '0' so it doesn't work. I have fixed that in the code now.  So now use `python3 tracker.py --video 0 --cam Y` whenever you want to use your webcam. Hopefully this should be fixed now. Sorry for the late response.

**Comment by ykn96** [comment]
@ankit16-py  hey thanks man.
